baseURL: www.owenmastalir.com
title: Owen Mastalir
theme: meghna-hugo
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: []
params:
  author: Themefisher
  cookies:
    enable: no
    expire_days: 2
  description: Owen Mastalir's Personal Website
  google_analytics_id: ''
  logo: images/Picture1.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  post_share: yes
  preloader:
    enable: no
    preloader: images/logo.png
  social:
    - icon: ti-facebook
      link: 'https://www.facebook.com/profile.php?id=100006967668570'
    - icon: ti-linkedin
      link: 'https://www.linkedin.com/in/owen-mastalir/'
    - icon: ti-github
      link: 'https://github.com/omastalir'
      
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 Designed by me using [Themefisher](https://themefisher.com)
      & Developed with [Hugo](https://gethugothemes.com)/[Netlify](https://www.netlify.com/)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: Work Experience
          url: '#team'
          weight: 1
        - name: Personal Life
          url: '#about'
          weight: 2  
        - name: Contact Info
          url: '#contact'
          weight: 3
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
